use native select for Dropdown component
conversation/ui pull request #140
Opened 2020-12-03 14:02 UTC by tiagoamaro

**Why?**

MUI custom select creates too much friction for users and test utilities. Let's use the native version instead.

If we want to use it anyway, we can disable the native version by passing the `<Dropdown native={false} />` prop.

**How to test  it?**

- Checkout this branch
- Run storybook (e.g.: `make storybook`)
- Read the new documentation on "Dropdown" overview (e.g.: http://localhost:9001/?path=/story/dropdowns--overview)
- See the native select in action checking the "Dropdown" "States" stories (e.g.: http://localhost:9001/?path=/story/dropdowns--states)

2020-12-04 00:21 UTC, benmacleod commented on src/Dropdown/Dropdown.jsx
> + * , rendering MUI's native `Select` by default. Keep in mind that non-native
```suggestion
 * rendering MUI's native `Select` by default. Keep in mind that non-native
```

2020-12-04 00:35 UTC, benmacleod requested changes
Looks good, and it's a good idea to allow the native implementation, especially since we're already using it in the wild in donations.

Is there actually still a use case for the non-native implementation? Given that it makes for complex testing maybe without benefits, should we actually get rid of non-native dropdowns? Would that break anything if this library suddenly switched?

If we do continue offering non-native dropdowns, we should probably show them in the `Dropdown` stories. Maybe as a variant on a "variants" page like `src/Button/stories/variants.jsx`?

2020-12-04 13:16 UTC, tiagoamaro commented
@benmacleod, I think it's unlikely we'll use the non-native variant, but documenting that it's available as it's a simple replication of MUI's `Select` component is a really nice idea!

Liked the `stories/variants.jsx` approach. Will add it to the PR!

2020-12-06 21:38 UTC, benmacleod approved these changes

2020-12-06 21:42 UTC, benmacleod approved these changes
If we are definitely going to allow non-native `Dropdown`s (which seems fine to me), then I think this is the best way to expose and document them 👍🏻

2020-12-06 21:42 UTC, merged